neo-1459: update to node 18 and fix storybook scripts
avaya-dux/neo-react-library pull request #140
Opened 2023-02-10 16:57 UTC by yangAtSpoken

[Link to updated components in Deploy Preview](https://deploy-preview-140--neo-react-library-storybook.netlify.app/)

**Before tagging the team for a review, I have done the following:**
- [x] reviewed my code changes
- [x] ensured that all tests pass
- [x] updated the link at the top of this PR (or remove it if not applicable)
- [x] added any important information to this PR (description, images, GIFs, ect.)
- [x] tagged Matt if any visual changes have occurred
- [x] done an accessibility check on my work

Update node to 19.6.0; 

Note: dev needs to have node 19.6.0 locally installed.

2023-02-10 17:26 UTC, Barbacoa08 requested changes
We should be using LTS IMO, [which is 18](https://nodejs.org/en/).

2023-02-10 17:28 UTC, Barbacoa08 commented on .nvmrc
> +19.6.0
I've not seen a `.nvmrc` file before. I did a quick search and I think that this is simply telling NVM to use Node `v19.6.0`. Is that correct?

2023-02-10 17:28 UTC, yangAtSpoken commented on .nvmrc
> +19.6.0
Used by netlify

2023-02-10 17:31 UTC, Barbacoa08 commented on package.json
> +    "@storybook/manager-webpack5": "^6.5.16",
nit: pin these versions. Mend will do it automatically when it does its weekly check, so this is very nitpicky, but it feels like a good habit to have.

2023-02-10 17:31 UTC, yangAtSpoken commented
> We should be using LTS IMO, [which is 18](https://nodejs.org/en/).

Renovate was using the latest node. if we use 18 here, it will update to 19.6.0 next chance it gets.

https://github.com/avaya-dux/neo-react-library/pull/137

2023-02-10 17:37 UTC, joe-s-avaya commented on .nvmrc
> +19.6.0
it does _not_ affect local machines then?

2023-02-10 17:40 UTC, joe-s-avaya commented
> > We should be using LTS IMO, [which is 18](https://nodejs.org/en/).
> 
> Renovate was using the latest node. if we use 18 here, it will update to 19.6.0 next chance it gets.
> 
> #137

To keep that from happening, we can use the `engines` field in `package.json` ([Mend docs](https://docs.renovatebot.com/node/))

2023-02-10 18:00 UTC, yangAtSpoken commented on .nvmrc
> +19.6.0
works on my local with or without it.

2023-02-10 18:03 UTC, joe-s-avaya commented on .nvmrc
> +19.6.0
My question is not if it works, but what it's purpose is. Is it's purpose to _only_ affect what version of Node that Netlify uses? Or is its purpose to affect every machine, including my machine when I run commands locally?

And then, is it doing that successfully?

2023-02-13 15:10 UTC, yangAtSpoken commented on .nvmrc
> +19.6.0
It tells Netlify to use the version specified in the file.  Locally, it affects only nvm commands, such as `nvm use`.

2023-02-13 15:10 UTC, yangAtSpoken commented on .nvmrc
> +19.6.0
Yes. it works successfully in both cases.

2023-02-13 15:15 UTC, yangAtSpoken commented on package.json
> +    "build:storybook": "NODE_OPTIONS=--openssl-legacy-provider build-storybook",
This tells Node (versions higher than 16) to load legacy code which is still needed by Storybook. Otherwise, we see the [digital envelope error](https://www.newline.co/@kchan/how-to-fix-the-error-errorerror0308010cdigital-envelope-routinesunsupported--0f8d3f17)

2023-02-13 15:16 UTC, yangAtSpoken commented on package.json
> +    "@storybook/manager-webpack5": "^6.5.16",
done.

2023-02-13 17:28 UTC, joe-s-avaya approved these changes

2023-02-13 18:12 UTC, merged