NEO-1075: LeffNav->TopLink: Active state is now driven by currentUrl value
avaya-dux/neo-react-library pull request #20
Opened 2022-08-22 21:26 UTC by enrique-prado

**Before tagging the team for a review, I have done the following:**
- [x ] reviewed my code changes
- [x] ensured that all tests pass
- [x ] added any important information to this PR (description, images, GIFs, ect.)
- [x] tagged Matt if any visual changes have occurred
- [x ] done an accessibility check on my work

We now update the TopLink active state if the currentUrl matches the url for that TopLinkItem

![2022-08-22 14 24 34](https://user-images.githubusercontent.com/3535271/186021868-9abb4ab8-3607-4e09-b159-29f75b6eb026.gif)

2022-08-22 21:35 UTC, matthewAvaya commented
From your Gif example, it works as expected.

2022-08-22 21:43 UTC, matthewAvaya approved these changes

2022-08-23 14:05 UTC, joe-s-avaya commented on src/components/LeftNavigation/TopLinkItem/TopLinkItem.tsx
> +  }, [ctx.currentUrl]);
I don't think that this is doing what you think it's doing. The URL in the stories is not updating, but the active state is, and this looks like it's comparing a partial URI to a full URI.

2022-08-23 14:06 UTC, joe-s-avaya requested changes
URL is not updated, which does not match what you describe in the PR description.
![2022-08-23 07 05 59](https://user-images.githubusercontent.com/55896546/186179511-78c8942d-f6b3-4d43-9acc-7ce20080017c.gif)

2022-08-23 14:35 UTC, yangAtSpoken commented on src/components/LeftNavigation/TopLinkItem/TopLinkItem.tsx
> +  }, [ctx.currentUrl]);
nit: put setIsActive and href in []

2022-08-23 14:35 UTC, yangAtSpoken approved these changes

2022-08-23 17:52 UTC, enrique-prado commented on src/components/LeftNavigation/TopLinkItem/TopLinkItem.tsx
> +  }, [ctx.currentUrl]);
added setIsActive and href to dep array.

2022-08-23 20:21 UTC, joe-s-avaya approved these changes

2022-08-23 21:19 UTC, merged