NEO-1804 PR #2
avaya-dux/neo-react-library pull request #242
Opened 2023-08-22 14:21 UTC by mrazian85

[Link to updated components in Deploy Preview](UPDATEMEWITHALINK)

**Before tagging the team for a review, I have done the following:**
- [ ] reviewed my code changes
- [ ] ensured that all tests pass
- [ ] updated the link at the top of this PR (or remove it if not applicable)
- [ ] added any important information to this PR (description, images, GIFs, ect.)
- [ ] tagged Matt if any visual changes have occurred
- [ ] done an accessibility check on my work

Put the most important information here. The content that any reviewer should see and read first (after the PR title).

**EXAMPLE IMAGE(S):**
[PUT EXAMPLES HERE, such as an image of the new tests, or important use case added by this update]

**EXAMPLE FUNCTIONALITY GIF:**
[PUT EXAMPLE GIF HERE]

**IMPORTANT NOTES:**
- Put any secondary, but still important, notes here
- May be bullets or a single sentence/paragraph

2023-08-22 20:39 UTC, yangAtSpoken commented on src/components/Notification/Notification.tsx
> +    : ReactDOM.createPortal(notification, document.body);
We should still use PopupManager to position the notification when it is not inline.  In storybook, we have a couple of stories under PopupManager -> Notification. There is also a hook, usePopup, that simplifies this a bit.

2023-08-22 20:40 UTC, yangAtSpoken requested changes
Left a comment.

2023-08-23 18:07 UTC, joe-s-avaya commented on src/components/Notification/Actions/ButtonAction/SecondaryButton.tsx
> +  notificationType,
should this have a default?

2023-08-23 18:09 UTC, joe-s-avaya commented on src/components/Notification/Notification.tsx
> +  function handleResize() {
nit: for consistency I recommend using arrow methods
```suggestion
  const handleResize = () => {
```

2023-08-23 18:10 UTC, joe-s-avaya commented on src/components/Notification/Notification.tsx
> +    translations?.closeAction,
your translations all have defaults yes? you shouldn't need the `?`

2023-08-23 18:13 UTC, joe-s-avaya commented on src/components/Notification/ToggleNotification.stories.tsx
> +          isInline={false}
nit: maybe have `false` be the default? would that simplify the usage?

2023-08-23 18:17 UTC, joe-s-avaya approved these changes
There are some nits and one bug, but I won't block. They're all quick and easy so I assume that you'll take care of it before merging.

2023-08-24 21:57 UTC, matthewAvaya commented
Two late updates from the team.
- Make both the header and the body copy to be 2 lines worth before truncation. Applies to both general and inline.
- Increase the padding between the header and the body copy to be 4 px. Applies to both general and inline.

Additional comments: 
- I'm not seeing a tooltip when hovering over the badge.

2023-08-25 21:27 UTC, mrazian85 commented on src/components/Notification/Notification.tsx
> +    : ReactDOM.createPortal(notification, document.body);
Great point; I have restored use of PopupManager to display the notification by moving the render logic outside of the Component itself and updating the stories in `PopupManager.notification.stories.tsx`.

I have also added a default width for the Notification when used with PopUpManager and allowed the user to pass in their own width for custom styling in order to preserve the way text truncation logic is handled

2023-08-25 21:27 UTC, mrazian85 commented on src/components/Notification/Actions/ButtonAction/SecondaryButton.tsx
> +  notificationType,
Good call; I have added one ✅

2023-08-25 21:30 UTC, mrazian85 commented on src/components/Notification/Notification.tsx
> +    translations?.closeAction,
The translations do have defaults, but these are handled by the `defaultTranslations` import

The `translations` prop itself is optional

2023-08-25 21:32 UTC, mrazian85 commented on src/components/Notification/Notification.tsx
> +  function handleResize() {
Actually ended up moving this method out of the Component as I had to refactor the logic to resolve some issues when using the PopUpManager for non-inline Notifications

As an aside, I think that makes this and other methods in the file easier to unit tests, although I haven't added any tests for them in this PR as it is already quite large. I think I will either create a third PR for this, or come back and add these tests after completing the work in the CSS library, as this ticket has already ballooned quite a bit due to changing AC

2023-08-25 21:32 UTC, mrazian85 commented on src/components/Notification/ToggleNotification.stories.tsx
> +          isInline={false}
Yes, good call ✅

2023-08-25 21:38 UTC, mrazian85 commented
> Two late updates from the team.
> 
> * Make both the header and the body copy to be 2 lines worth before truncation. Applies to both general and inline.
> * Increase the padding between the header and the body copy to be 4 px. Applies to both general and inline.
> 
> Additional comments:
> 
> * I'm not seeing a tooltip when hovering over the badge.

@matthewAvaya all feedback should be picked up now, except for the padding between header and body was already at 4px as far as I could tell

2023-08-25 21:48 UTC, matthewAvaya approved these changes
Looks great!

2023-08-25 22:54 UTC, yangAtSpoken approved these changes

2023-08-28 14:06 UTC, merged