NEO-1834 clicking on chevron should open select dropdown
avaya-dux/neo-react-library pull request #243
Opened 2023-08-29 15:02 UTC by yangAtSpoken

[Link to updated components in Deploy Preview](UPDATEMEWITHALINK)

**Before tagging the team for a review, I have done the following:**
- [ ] reviewed my code changes
- [ ] ensured that all tests pass
- [ ] updated the link at the top of this PR (or remove it if not applicable)
- [ ] added any important information to this PR (description, images, GIFs, ect.)
- [ ] tagged Matt if any visual changes have occurred
- [ ] done an accessibility check on my work

2023-08-29 15:18 UTC, joe-s-avaya commented on src/components/Select/InternalComponents/MultiSelect.tsx
> +      <span className="neo-multiselect-combo__header  neo-multiselect-combo__header--no-after">
nit: extra space
```suggestion
      <span className="neo-multiselect-combo__header neo-multiselect-combo__header--no-after">
```

2023-08-29 15:19 UTC, joe-s-avaya commented on src/components/Select/Select.cy.tsx
> +  it("Last fruit in the list becomes visible with arrow downs", () => {
good eye!

2023-08-29 16:57 UTC, enrique-prado requested changes
There are a couple of things that broke in the multiple select behavior:

1. After you make selections, you can no longer close the dropdown by clicking on the chevron. 
2. Keyboard users can no longer close the dropdown with the ESC key.

2023-08-29 19:06 UTC, matthewAvaya commented
Overall it's looking good. For voice-over, the selection gets read twice on a lot of these. Please take a look at the screenshot for an example.
<img width="685" alt="Screen Shot 2023-08-29 at 12 04 36 PM" src="https://github.com/avaya-dux/neo-react-library/assets/90473510/99575663-6429-4b81-b4da-5b460f506694">

2023-08-31 14:33 UTC, yangAtSpoken commented
> Overall it's looking good. For voice-over, the selection gets read twice on a lot of these. Please take a look at the screenshot for an example. <img alt="Screen Shot 2023-08-29 at 12 04 36 PM" width="685" src="https://user-images.githubusercontent.com/90473510/264126898-99575663-6429-4b81-b4da-5b460f506694.png">

@matthewAvaya If this is not a regression, let us create a new ticket to track this.

2023-08-31 14:35 UTC, yangAtSpoken commented
> There are a couple of things that broke in the multiple select behavior:
> 
> 1. After you make selections, you can no longer close the dropdown by clicking on the chevron.
> 2. Keyboard users can no longer close the dropdown with the ESC key.

@enrique-prado For 1, you can no longer click chevron to close dropdown as chevron is part of the button now.  And the button right now does not toggle. 2. ESC key works for me. You have to show me how it is not working you.

2023-08-31 17:36 UTC, matthewAvaya commented
> > Overall it's looking good. For voice-over, the selection gets read twice on a lot of these. Please take a look at the screenshot for an example. <img alt="Screen Shot 2023-08-29 at 12 04 36 PM" width="685" src="https://user-images.githubusercontent.com/90473510/264126898-99575663-6429-4b81-b4da-5b460f506694.png">
> 
> @matthewAvaya If this is not a regression, let us create a new ticket to track this.

Thanks @yangAtSpoken for creating the new ticket.

2023-08-31 17:36 UTC, matthewAvaya commented
> > There are a couple of things that broke in the multiple select behavior:
> > 
> > 1. After you make selections, you can no longer close the dropdown by clicking on the chevron.
> > 2. Keyboard users can no longer close the dropdown with the ESC key.
> 
> @enrique-prado For 1, you can no longer click chevron to close dropdown as chevron is part of the button now. And the button right now does not toggle. 2. ESC key works for me. You have to show me how it is not working for you.

Did this get resolved? The ESC key works for me as well to close the dropdown menu.

2023-08-31 19:12 UTC, enrique-prado commented
@matthewAvaya Regarding #2, I can only repro the ESC issue if I use the mouse to make selections. That's because using the mouse does not give the select component focus.  But since keyboard users use the keyboard to make selections and in that scenario the ESC key works I'm going to approve this PR.  If you can open a ticket for the mouse click / focus issue that would be great. thanks.

2023-08-31 19:13 UTC, enrique-prado approved these changes

2023-08-31 19:19 UTC, enrique-prado commented on src/components/Select/utils/useDownshift.ts
> +      const isOpen = changes.isOpen ? !(disabled || loading) : false
Nice!

2023-08-31 19:20 UTC, matthewAvaya commented
> @matthewAvaya Regarding #2, I can only repro the ESC issue if I use the mouse to make selections. That's because using the mouse does not give the select component focus. But since keyboard users use the keyboard to make selections and in that scenario the ESC key works I'm going to approve this PR. If you can open a ticket for the mouse click / focus issue that would be great. thanks.

I see, good catch. Okay, I'll create a new Jira for this. In this case, I'll go ahead and approve the PR as well. Thanks!

2023-08-31 19:20 UTC, matthewAvaya approved these changes

2023-09-01 13:32 UTC, merged