Update Checkbox functionality to be more DX friendly
avaya-dux/neo-react-library pull request #70
Opened 2022-11-08 20:27 UTC by joe-s-avaya

[Link to updated components in Deploy Preview](UPDATEMEWITHALINK)

**Before tagging the team for a review, I have done the following:**
- [ ] reviewed my code changes
- [ ] ensured that all tests pass
- [ ] updated the link at the top of this PR (or remove it if not applicable)
- [ ] added any important information to this PR (description, images, GIFs, ect.)
- [ ] tagged Matt if any visual changes have occurred
- [ ] done an accessibility check on my work

Put the most important information here. The content that any reviewer should see and read first (after the PR title).

**EXAMPLE IMAGE(S):**
[PUT EXAMPLES HERE, such as an image of the new tests, or important use case added by this update]

**EXAMPLE FUNCTIONALITY GIF:**
[PUT EXAMPLE GIF HERE]

**IMPORTANT NOTES:**
- Put any secondary, but still important, notes here
- May be bullets or a single sentence/paragraph

2022-11-09 17:17 UTC, yangAtSpoken commented on src/components/Checkbox/Checkbox.tsx
> +          aria-label={ariaLabel || (children as string)}
Casting children as string may not work well.  Maybe a 3rd party tool like https://github.com/sunknudsen/react-node-to-string
could help.

2022-11-09 17:21 UTC, yangAtSpoken commented on src/components/Checkbox/Checkbox.tsx
> +        <label htmlFor={id}>{children}</label>
This could be a good question for Terri today.  But the answer in this page says not many things could be children of <label>, https://stackoverflow.com/questions/18609554/is-div-inside-label-block-correct

2022-11-09 17:39 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +    [groupName]
missing label

2022-11-09 17:43 UTC, joe-s-avaya commented on src/components/Checkbox/Checkbox.tsx
> +        <label htmlFor={id}>{children}</label>
I think you meant to write that the `<label>` tag should only contain a small subset of other HTML elements. Which isn't really a Terri question as she isn't a code person, but you could ask her, I just don't think that she'd know the answer.

But either way, I didn't change anything about what is passed into the `<label>` tag. It was originally `string | JSX.Element`, which is equivalent to `ReactNode`. So nothing has changed here, and if you want me to restrict the possible passed elements to a specific set, I think that should be a different PR. I'm also hesitant to do that as I'm not seeing a well written explanation of _exactly_ what children are and are not allowed. 
(from looking at [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) and the [html-spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element))

2022-11-09 17:44 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +    [groupName]
I don't understand what you're saying here. If `label` exists, and there is no `groupName`, I use a modified label. Else, I know from the typings (and a11y `if` guard) that the `groupName` _must_ exist, and I use that.
Are you saying that there is a bug in my logic? I have tests for this, so it _should_ all be correct.

2022-11-09 17:46 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label && !groupName ? label.toLowerCase().replace(" ", "-") : groupName,
Oh, that's a great simplification. Will make the update.

2022-11-09 17:49 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label && !groupName ? label.toLowerCase().replace(" ", "-") : groupName,
updated

2022-11-09 18:46 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
A label is usually associated with one input control.  The label in CheckboxGroup is not associated with any checkboxes inside this group.  It just displays group name.  I would suggest a boolean property, showGroupName (default to true), instead.

2022-11-09 18:52 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +    [groupName]
It is not about handleAccessbilityError checking.  It is that general rule, i.e. whatever vars used inside a hook need to be in the dependency list.

2022-11-09 19:03 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      groupName?: string;
groupName should be a required field for a checkbox group.

2022-11-09 19:04 UTC, yangAtSpoken requested changes
To hide group name, use a boolean instead as label is not an accessibility requirement for a checkbox group.

2022-11-09 19:17 UTC, enrique-prado reviewed
Just the one question about the children type.

2022-11-09 19:17 UTC, enrique-prado commented on src/components/Checkbox/Checkbox.tsx
> +      children?: ReactNode;
If you are casting children as string down in line 100, why not make children type 'string' instead?

2022-11-09 19:31 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +    [groupName]
Yes, that makes sense, updated. I didn't understand what you were asking for.

2022-11-09 19:38 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
No for two reasons. 

One, a "label" should be a label and nothing more. Previously, we were inappropriately using the `groupName` as the `for`, "label", and `name`. Now, `label` is just the label of the group.*
Two, the `groupName` is the `name` prop of every checkbox in the group, and the `for` used on the `label`.

Thus, we should not use a boolean because the `for`+`name` need to be specific and follow best practices (ie, no spaces), and we need to allow the passing of one or both of `label` and `groupName`.

* unless no `groupName` is passed, then we modify the `label` to follow best practices and use that generated value for the `for`+`name` props. But even under that circumstance, the "label" is still just a label. We could just as easily use a generated value for the same, but this approach makes the DX slightly easier if you're looking through the DOM code.

2022-11-09 19:39 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
Also, the `label` in this case is associated with one "group" of inputs, as I believe is the best practice for both groups of checkboxes and groups of radio buttons.

2022-11-09 19:40 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      groupName?: string;
Why? We can easily generate it, there's no reason to force the user to pass it that I can think of.

2022-11-09 19:48 UTC, joe-s-avaya commented on src/components/Checkbox/Checkbox.tsx
> +      children?: ReactNode;
Fair question. I'm not sure if that passing `children` to the aria-label is correct, but there's a test for it so I don't want to undo that functionality as I presume that the original implementor knew what they were doing. Also, I don't want to force the `children` to be just a `string` as that would also remove previous functionality. 

However, you make a good point. So I've updated line 100 to only use `children` if it is a string type.

2022-11-09 19:49 UTC, joe-s-avaya commented on src/components/Checkbox/Checkbox.tsx
> +          aria-label={ariaLabel || (children as string)}
updated

2022-11-09 19:56 UTC, enrique-prado commented on src/components/Checkbox/Checkbox.tsx
> +      children?: ReactNode;
ok, sounds good to me.

2022-11-09 19:59 UTC, enrique-prado approved these changes

2022-11-10 13:54 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
No, for + name is in correct. for + id is the correct combination.

2022-11-10 13:57 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      groupName?: string;
groupName is submitted to backend in groupName=value1+value2 form.  It should not be generated.

2022-11-10 15:28 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
@yangAtSpoken, the generated name is `htmlForName` on line 83. It is then used on lines 108, the `Checkbox` `name` fields, and line 116 the `htmlFor`/`for` `label` prop. Where do you see it being used as an `id` prop?

2022-11-10 15:31 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      groupName?: string;
@yangAtSpoken yes, but only if the user uses the default form and submit, which very rarely happens in my experience. And they are allowed to pass the group name, it's just not required. Thus, because people rarely use the default form submit, it shouldn't be required.

2022-11-10 19:41 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      groupName?: string;
I do not agree here. I think submit data correctly is the most important thing for a form control.  Thus do not the user guess what the group name is from a label.  And the label you added is not an accessibility requirement for this control.

2022-11-10 19:45 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
I am just saying htmlForName is not a good name. The better name here is groupName, which is already passed in.  Besides htmlFor is usually associate with a control's id.  So htmlForName seems a misnomer to me.

2022-11-10 19:58 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      {label && <label htmlFor={htmlForName}>{label}</label>}
htmlFor bounds to an element id, [label for attribute](https://www.w3schools.com/tags/att_label_for.asp)

2022-11-10 20:00 UTC, yangAtSpoken commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +        name={htmlForName}
htmlForName will end up on the "name" attribute of the checkbox.  It should end in id attribute for accessibility.  But checkbox already has a label.

2022-11-11 16:22 UTC, joe-s-avaya commented on src/components/CheckboxGroup/CheckboxGroup.tsx
> +      label: string;
Per our discussion, will deal with in another PR as this will require a larger update

2022-11-11 16:23 UTC, joe-s-avaya commented
@yangAtSpoken, I'll deal with the a11y `label` for the group in another PR (per our discussion), and I think that I've dealt with all of the other issues you've seen. Please take another look and let me know if there's anything else you want me to update in this PR or the next one.

2022-11-14 14:50 UTC, merged